# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: Toward Generating Experiment-Specific Notebooks in FABRIC
author: Mami Hayashida, Joshna Kurra, Zongming Fei, and James Griffioen
copyright: "2025" # Copyright year to be placed in the footer
logo: assets/iss2025.png # Path to a logo image

# Patterns to skip when building the book. Can be glob-style (e.g. "*skip.ipynb")
exclude_patterns: [_build, Thumbs.db, .DS_Store, "**.ipynb_checkpoints"]

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html

execute:
  execute_notebooks: "off"
  timeout: 600
  exclude_patterns: # A list of patterns to *skip* in execution (e.g. a notebook that takes a really long time)
    - "*dont-execute*"
  allow_errors: true
  stderr_output: remove-warn

# Add a few extensions to help with parsing content
parse:
  myst_enable_extensions: # default extensions to enable in the myst parser. See https://myst-parser.readthedocs.io/en/latest/using/syntax-optional.html
    - amsmath
    - colon_fence
    - deflist
    - dollarmath
    - html_admonition
    - html_image
    - replacements
    - smartquotes
    - substitution

# Define the name of the latex output file for PDF builds
latex:
  latex_engine: pdflatex # one of 'pdflatex', 'xelatex' (recommended for unicode), 'luatex', 'platex', 'uplatex'
  use_jupyterbook_latex: true # use jupyterbook-latex for pdf builds as default
  latex_documents:
    targetname: sea_paper_2024.tex

bibtex_bibfiles:
  - references.bib

# Information about where the book exists on the web
repository:
  url: https://github.com/UCAR-SEA/SEA-ISS-2025-Toward-Generating-Experiment-Specific-Notebooks-in-Fabric # Online location of your book
  #path_to_book:  # Optional path to your book, relative to the repository root
  branch: main # Which branch of the repository should be used when creating links (optional)

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  favicon: "assets/2024_SEA_Logo2.png" # A path to a favicon image
  use_repository_button: true
  use_edit_page_button: true
  use_issues_button: true
  home_page_in_navbar: true
  use_multitoc_numbering: true # Continuous numbering across parts/chapters

  comments:
    hypothesis: false
    utterances: false

sphinx:
  config:
    html_last_updated_fmt: "%-d %B %Y"
    html_theme: sphinx_pythia_theme
    html_permalinks_icon: '<i class="fas fa-link"></i>'
    bibtex_reference_style: author_year
    html_theme_options:
      home_page_in_toc: true
      repository_url: https://github.com/UCAR-SEA/SEA-ISS-2025-Toward-Generating-Experiment-Specific-Notebooks-in-Fabric # Online location of your book
      repository_branch: main
      navbar_align: right
      search_bar_text: Search
      use_issues_button: true
      use_repository_button: true
      use_edit_page_button: true
      use_download_button: true
      use_fullscreen_button: true
      github_url: https://github.com/UCAR-SEA
      extra_navbar: |
        <div>Powered by <a href="https://jupyterbook.org">Jupyter Book</a></div>Theme adapted from <a href="https://projectpythia.org/">Project Pythia</a>

      navbar_links:
        - name: SEA Home
          url: https://sea.ucar.edu
        - name: ISS Conference
          url: https://sea.ucar.edu/iss/2025/
        - name: ISS Proceedings
          url: https://sea.ucar.edu/iss/2025-proceedings

    html_sidebars:
      banner: []
      standalone: []

